FROM node:alpine
 
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

# add permissions for wsl to run react-scripts (significantly increases build time)
#RUN ["chmod", "-R", "a+x", "node_modules/"]
#RUN chmod a+x node_modules/.bin/react-scripts
#RUN chmod -R a+x node_modules/react-scripts/

CMD ["npm", "run", "start"]