FROM node:alpine
 
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

RUN ["chmod", "-R", "a+x", "node_modules/react-scripts"]

CMD ["npm", "run", "start"]