name: Deploy Multidocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # login to docker CLI
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # build and run client react tests
      - run: docker build -t samcdonovan/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true samcdonovan/react-test npm test
 
      # build service images
      - run: docker build -t samcdonovan/multi-client-10-14 ./client
      - run: docker build -t samcdonovan/multi-nginx-10-14 ./nginx
      - run: docker build -t samcdonovan/multi-server-10-14 ./server
      - run: docker build -t samcdonovan/multi-worker-10-14 ./worker
 
      # push images to dockerHub
      - run: docker push samcdonovan/multi-client-10-14
      - run: docker push samcdonovan/multi-nginx-10-14
      - run: docker push samcdonovan/multi-server-10-14
      - run: docker push samcdonovan/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react-CI
          environment_name: Dockerreactci-env
          existing_bucket_name: elasticbeanstalk-us-east-1-784713347581
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip